using Itaiji.Generator;
using System;
using System.Collections.Generic;
using System.Text;
using Itaiji;

namespace Itaiji.Generator;

internal static class IvdSequences
{
    public static void Execute()
    {
        var text = File.ReadAllText("IVD_Sequences.txt");

        var dic = new Dictionary<(Rune, Rune), IvsCollectionType>();
        foreach (var line in text.Split(["\n"], StringSplitOptions.None))
        {
            if (line.StartsWith("#"))
            {
                continue;
            }

            if (line.Trim() == "")
            {
                continue;
            }

            var cols = line.Split(';');
            var runes = cols[0].Split(' ');

            var firstRune = new Rune(Convert.ToInt32(runes[0], 16));
            var secondRune = new Rune(Convert.ToInt32(runes[1], 16));

            var t = (firstRune, secondRune);

            var type = cols[1].Trim() switch
            {
                "Adobe-Japan1" => IvsCollectionType.AdobeJapan,
                "Hanyo-Denshi" => IvsCollectionType.HanyoDenshi,
                "Moji_Joho" => IvsCollectionType.MojiJoho,
                "CAAPH" => IvsCollectionType.CAAPH,
                "KRName" => IvsCollectionType.KRName,
                "MSARG" => IvsCollectionType.MSARG,

                _ => IvsCollectionType.Unknown
            };
            if (type == IvsCollectionType.Unknown)
            {
                //Console.WriteLine(cols[1]);
                continue;
            }

            if (dic.ContainsKey(t) == false)
            {
                dic[t] = IvsCollectionType.None;
            }
            dic[t] |= type;
        }

        var builder = new StringBuilder();
        builder.AppendLine($$"""
    // <auto-generated />
    namespace Itaiji;

    internal static partial class Library
    {
    #if NET40_OR_GREATER
        private static Lazy<SortedList<int, int>> _JpIvsList = new Lazy<SortedList<int, int>>(GetJpIvsList, isThreadSafe: true);
        public static SortedList<int, int> JpIvsList => _JpIvsList.Value;
    #else
        private static SortedList<int, int> _JpIvsList;
        public static SortedList<int, int> JpIvsList => _JpIvsList ??= GetJpIvsList();
    #endif
        private static SortedList<int, int> GetJpIvsList() 
        {
            return new SortedList<int, int>({{dic.Count}})
            {
    """);

        var cnt = 0;
        foreach (var kvp in dic.OrderBy(x => x.Key.Item1).ThenBy(x => x.Key.Item2))
        {
            if (cnt % 10 == 0)
            {
                builder.Append("        ");
            }
            var key = (kvp.Key.Item1.Value << 8) | ((kvp.Key.Item2.Value & 0xFF));
            var value = (int)kvp.Value;
            builder.Append($"{{0x{key:X},{value}}},");
            if (cnt % 10 == 9)
            {
                builder.AppendLine();
            }
            cnt++;

        }
        builder.AppendLine("""
            };
        }
    }
    """);

        File.WriteAllText("Library.cs", builder.ToString());
    }
}
