using Kanji.Generator;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace Itaiji.Generator;

internal static class StandardizedVariants
{
    public static void Execute()
    {
        
        var text = File.ReadAllText("StandardizedVariants.txt");

        var flg = false;
        var dic= new Dictionary<int, int>();
        foreach (var line in text.Split(["\n"], StringSplitOptions.None))
        {
            if(line == "# CJK compatibility ideographs")
            {
                flg = true;
            }
            if(!flg)
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(line) || line.StartsWith("#"))
            {
                continue;
            }

            var parts = line.Split(';');

            var baseChar = Regex.Match(parts[1], @"IDEOGRAPH-(.+)").Groups[1].Value;
            var tochar = parts[0].Split(' ')[0];
            var toSvsChar = parts[0].Split(' ')[1];

            var baseInt = Convert.ToInt32(baseChar, 16);
            var toInt = (Convert.ToInt32(tochar, 16) << 8) | ((Convert.ToInt32(toSvsChar, 16) & 0xFF) + 0xF0);
            dic.Add(baseInt, toInt);
        }

        var sbuilder = new StringBuilder();

        sbuilder.AppendLine($$"""
    // <auto-generated />
    namespace Itaiji;
    internal static partial class Library
    {
        public static HashSet<int> StandardizedVariants => _StandardizedVariants ??= GetStandardizedVariants(); 
        private static HashSet<int> _StandardizedVariants;
        private static HashSet<int> GetStandardizedVariants() => [
    """);
        var cnt = 0;
        foreach (var kv in dic.OrderBy(x => x.Value))
        {
            cnt++;
            if(cnt % 10 == 1)
            {
                sbuilder.Append("        ");
            }
            sbuilder.Append($"0x{kv.Value:X}, ");
            if(cnt % 10 == 0)
            {
                sbuilder.AppendLine();
            }
        }
        sbuilder.AppendLine();
        sbuilder.AppendLine("""
        ];
    }
    """);
        File.WriteAllText("Library_JpStandardizedVariants.cs", sbuilder.ToString());
      
    }
}
